/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chapter {
  'name' : string,
  'totalPages' : bigint,
  'isComplete' : boolean,
}
export interface StudyTarget {
  'subjects' : Array<string>,
  'date' : Time,
  'chapters' : Array<[string, string]>,
  'isComplete' : boolean,
}
export interface Subject { 'name' : string, 'chapters' : Array<Chapter> }
export type Time = bigint;
export interface _SERVICE {
  'addChapter' : ActorMethod<[string, string, bigint], undefined>,
  'addSubject' : ActorMethod<[string], undefined>,
  'completeChapter' : ActorMethod<[string, string], undefined>,
  'completeStudyTarget' : ActorMethod<[Time], undefined>,
  'getAllSubjects' : ActorMethod<[], Array<Subject>>,
  'getStudyTarget' : ActorMethod<[Time], StudyTarget>,
  'getStudyTargetsInRange' : ActorMethod<[Time, Time], Array<StudyTarget>>,
  'getSubject' : ActorMethod<[string], Subject>,
  'setStudyTarget' : ActorMethod<
    [Time, Array<string>, Array<[string, string]>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];