/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Chapter = IDL.Record({
  'name' : IDL.Text,
  'totalPages' : IDL.Nat,
  'isComplete' : IDL.Bool,
});
export const Subject = IDL.Record({
  'name' : IDL.Text,
  'chapters' : IDL.Vec(Chapter),
});
export const StudyTarget = IDL.Record({
  'subjects' : IDL.Vec(IDL.Text),
  'date' : Time,
  'chapters' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'isComplete' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addChapter' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'addSubject' : IDL.Func([IDL.Text], [], []),
  'completeChapter' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'completeStudyTarget' : IDL.Func([Time], [], []),
  'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getStudyTarget' : IDL.Func([Time], [StudyTarget], ['query']),
  'getStudyTargetsInRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(StudyTarget)],
      ['query'],
    ),
  'getSubject' : IDL.Func([IDL.Text], [Subject], ['query']),
  'setStudyTarget' : IDL.Func(
      [Time, IDL.Vec(IDL.Text), IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Chapter = IDL.Record({
    'name' : IDL.Text,
    'totalPages' : IDL.Nat,
    'isComplete' : IDL.Bool,
  });
  const Subject = IDL.Record({
    'name' : IDL.Text,
    'chapters' : IDL.Vec(Chapter),
  });
  const StudyTarget = IDL.Record({
    'subjects' : IDL.Vec(IDL.Text),
    'date' : Time,
    'chapters' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'isComplete' : IDL.Bool,
  });
  
  return IDL.Service({
    'addChapter' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'addSubject' : IDL.Func([IDL.Text], [], []),
    'completeChapter' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'completeStudyTarget' : IDL.Func([Time], [], []),
    'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getStudyTarget' : IDL.Func([Time], [StudyTarget], ['query']),
    'getStudyTargetsInRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(StudyTarget)],
        ['query'],
      ),
    'getSubject' : IDL.Func([IDL.Text], [Subject], ['query']),
    'setStudyTarget' : IDL.Func(
        [Time, IDL.Vec(IDL.Text), IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };